# Task-1

In [1]:
import pandas as pd
tickets=pd.read_csv("data_safe_copy.csv")

In [2]:
tickets.shape

(500, 5)

In [3]:
tickets.head()

  ticket_id         opened_at   category priority resolution_minutes
0   TK-0001  2024-03-01 09:00    billing      low                 45
1   TK-0002  2024-03-01 09:30    account   medium                 30
2   TK-0003  2024-03-01 10:00  technical     high                 75
3   TK-0004  2024-03-01 10:30    billing      low                NaN
4   TK-0005  2024-03-01 11:00    account   medium            unknown

In [4]:
tickets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ticket_id           500 non-null    object
 1   opened_at           500 non-null    object
 2   category            500 non-null    object
 3   priority            500 non-null    object
 4   resolution_minutes  450 non-null    object
dtypes: object(5)
memory usage: 19.7+ KB

# Task-2

In [5]:
tickets["opened_at"]=pd.to_datetime(tickets["opened_at"])

In [6]:
tickets

    ticket_id           opened_at   category priority resolution_minutes
0     TK-0001 2024-03-01 09:00:00    billing      low                 45
1     TK-0002 2024-03-01 09:30:00    account   medium                 30
2     TK-0003 2024-03-01 10:00:00  technical     high                 75
3     TK-0004 2024-03-01 10:30:00    billing      low                NaN
4     TK-0005 2024-03-01 11:00:00    account   medium            unknown
..        ...                 ...        ...      ...                ...
495   TK-0496 2024-03-01 11:30:00  TECHNICAL     high                 60
496   TK-0497 2024-03-01 12:00:00    billing    high                  15
497   TK-0498 2024-03-01 12:30:00    account      low                 90
498   TK-0499 2024-03-01 13:00:00  technical   medium                120
499   TK-0500 2024-03-01 13:30:00    billing   medium                 25

[500 rows x 5 columns]

In [7]:
tickets["category"]=tickets["category"].str.strip().str.lower()
tickets["priority"]=tickets["priority"].str.strip().str.lower()

In [8]:
tickets["category"].unique()

array(['billing', 'account', 'technical'], dtype=object)

In [9]:
tickets["priority"].unique()

array(['low', 'medium', 'high'], dtype=object)

# Task-3

In [10]:
tickets["resolution_minutes"]=pd.to_numeric(tickets["resolution_minutes"],errors="coerce")

In [11]:
tickets["resolution_minutes"].isna().sum()

np.int64(100)

# Task-4

In [12]:
tickets_clean=tickets.dropna(subset=["resolution_minutes"])
tickets_clean

    ticket_id           opened_at   category priority  resolution_minutes
0     TK-0001 2024-03-01 09:00:00    billing      low                45.0
1     TK-0002 2024-03-01 09:30:00    account   medium                30.0
2     TK-0003 2024-03-01 10:00:00  technical     high                75.0
5     TK-0006 2024-03-01 11:30:00  technical     high                60.0
6     TK-0007 2024-03-01 12:00:00    billing     high                15.0
..        ...                 ...        ...      ...                 ...
495   TK-0496 2024-03-01 11:30:00  technical     high                60.0
496   TK-0497 2024-03-01 12:00:00    billing     high                15.0
497   TK-0498 2024-03-01 12:30:00    account      low                90.0
498   TK-0499 2024-03-01 13:00:00  technical   medium               120.0
499   TK-0500 2024-03-01 13:30:00    billing   medium                25.0

[400 rows x 5 columns]

In [13]:
(tickets_clean["resolution_minutes"]>=0).all()

np.True_

In [14]:
print((tickets_clean["category"] == tickets_clean["category"].str.strip().str.lower()).all())

True

In [15]:
print((tickets_clean["priority"] == tickets_clean["priority"].str.strip().str.lower()).all())

True

In [16]:
print("Before cleaning: ", len(tickets))
print("After cleaning: ", len(tickets_clean))

Before cleaning:  500
After cleaning:  400

In [17]:
tickets_clean["resolution_minutes"].max()

120.0

# Task-5

In [18]:
total_records = len(tickets)
clean_records = len(tickets_clean)
missing_resolution = tickets["resolution_minutes"].isna().sum()

In [19]:
summary={
    "total_records":total_records,
    "clean_records": clean_records,
    "missing_resolution":missing_resolution,
    "avg_resolution": tickets_clean["resolution_minutes"].mean() ,
    "max_resolution": tickets_clean["resolution_minutes"].max()                  
}

In [20]:
print(f"""
total_records: {summary['total_records']}
clean_records: {summary['clean_records']}
missing_resolution: {summary['missing_resolution']}
avg_resolution: {summary['avg_resolution']}
max_resolution: {summary['max_resolution']}
""")

total_records: 500
clean_records: 400
missing_resolution: 100
avg_resolution: 57.5
max_resolution: 120.0

In [21]:
print(total_records==missing_resolution+clean_records)

True